# Generated by Django 5.1.2 on 2024-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='bot_response',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_message',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
    ]
