# Generated by Django 5.1.2 on 2024-10-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_text_message_bot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.TextField(null=True),
        ),
    ]
